execute-dir: project

project:
  type: website
  render:
    - index.qmd
    - slides/Slides_wk01.qmd
    - practices/wk01.qmd
    # - answers/wk01_answer.qmd
    - example_code/Example_Code_wk01.qmd
  resources:
    - slides/Slides_wk01.pdf
    - example_code/wk01_example_code.R
    - assets/audio/**

website:
  site-url: https://danny2915.github.io/2026QuantitativeTASession/
  title: "2026 基礎數量方法 TA Session"
  navbar: false
  page-navigation: true
  search: false

  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - text: "Home"
        file: index.qmd
      - section: "Slides"
        contents:
          - slides/Slides_wk01.qmd
      - section: "Example R code"
        contents:
          - example_code/Example_Code_wk01.qmd
      - section: "Practices"
        contents:
          - practices/wk01.qmd
      # - section: "Practice Answers"
      #   contents:
      #     - answers/wk01_answer.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
    page-layout: article
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
    embed-resources: false
    html-math-method: katex
    include-after-body:
      - assets/bgm.html
execute:
  warning: false
  message: false
